version: '3'

services:
  teambarometer-api:
    container_name: teambarometer-api
    image: raphadeveloper/teambarometer-api
    ports:
      - "5554:80"
    networks:
      - teambarometer-network

  teambarometer-ui:
    container_name: teambarometer-ui
    image: teambarometer-ui
    depends_on:
      - teambarometer-api
    ports:
      - "5555:80"
    networks:
      - teambarometer-network

networks: 
  teambarometer-network:
    driver: bridge